FROM nginx:latest

WORKDIR /usr/share/nginx

COPY ./app/Client/Controllers ./html/Controllers/
COPY ./app/Client/Styles ./html/Styles/
COPY ./app/Client/Views/CreateWordView.html ./html/
COPY ./app/Client/Views/WordListView.html ./html/
COPY ./app/Client/Views/index.html ./html/index.html
